const types = {    
    GLOBAL_STATUS_USER_TOKEN : 'GLOBAL_STATUS_USER_TOKEN',
    GLOBAL_STATUS_DRAWER_OPEN : 'GLOBAL_STATUS_DRAWER_OPEN',
    GLOBAL_STATUS_TOGGLE_CATEGORY : 'GLOBAL_STATUS_TOGGLE_CATEGORY',
    GLOBAL_STATUS_TOGGLE_PRODUCT : 'GLOBAL_STATUS_TOGGLE_PRODUCT',
    GLOBAL_STATUS_TOGGLE_NOTICE_DETAIL : 'GLOBAL_STATUS_TOGGLE_NOTICE_DETAIL',
    GLOBAL_STATUS_TOGGLE_BANNER_DETAIL : 'GLOBAL_STATUS_TOGGLE_BANNER_DETAIL',
    GLOBAL_STATUS_CHOICE_CATEGORY_ARRAY : 'GLOBAL_STATUS_CHOICE_CATEGORY_ARRAY',
    GLOBAL_STATUS_CHOICE_PRODUCT_ARRAY : 'GLOBAL_STATUS_CHOICE_PRODUCT_ARRAY',
    GLOBAL_STATUS_NOW_CATEGORYNAME : 'GLOBAL_STATUS_NOW_CATEGORYNAME',
    GLOBAL_STATUS_NOW_KEYBOARD_FOCUS : 'GLOBAL_STATUS_NOW_KEYBOARD_FOCUS'
}

export default types;
